/**
 * generated by Xtext 2.10.0
 */
package bsqllog2java.bSQLLog2Java.impl;

import bsqllog2java.bSQLLog2Java.BSQLLog2Java;
import bsqllog2java.bSQLLog2Java.BSQLLog2JavaPackage;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>BSQL Log2 Java</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class BSQLLog2JavaImpl extends MinimalEObjectImpl.Container implements BSQLLog2Java
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected BSQLLog2JavaImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return BSQLLog2JavaPackage.Literals.BSQL_LOG2_JAVA;
  }

} //BSQLLog2JavaImpl
