/*
 * generated by Xtext 2.10.0
 */
package bsql2java.ui.tests;

import bsql2java.ui.internal.Bsql2javaActivator;
import com.google.inject.Injector;
import org.eclipse.xtext.junit4.IInjectorProvider;

public class BSQL2JavaUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return Bsql2javaActivator.getInstance().getInjector("bsql2java.BSQL2Java");
	}

}
