/**
 * generated by Xtext 2.10.0
 */
package bsql2java;

import bsql2java.AbstractBSQL2Java2RuntimeModule;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class BSQL2Java2RuntimeModule extends AbstractBSQL2Java2RuntimeModule {
}
