/*
 * generated by Xtext 2.10.0
 */
package bsql2sql.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractBSQL2SQLScopeProvider extends DelegatingScopeProvider {
}
