/**
 * generated by Xtext 2.10.0
 */
package bsqllog2java;

import bsqllog2java.AbstractBSQLLog2JavaRuntimeModule;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class BSQLLog2JavaRuntimeModule extends AbstractBSQLLog2JavaRuntimeModule {
}
