/**
 * generated by Xtext 2.10.0
 */
package bsqllog2java.ui;

import bsqllog2java.ui.AbstractBSQLLog2JavaUiModule;
import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class BSQLLog2JavaUiModule extends AbstractBSQLLog2JavaUiModule {
  public BSQLLog2JavaUiModule(final AbstractUIPlugin plugin) {
    super(plugin);
  }
}
