/**
 * generated by Xtext 2.10.0
 */
package b2sql.b2SQL2;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>B2SQL2</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see b2sql.b2SQL2.B2SQL2Package#getB2SQL2()
 * @model
 * @generated
 */
public interface B2SQL2 extends EObject
{
} // B2SQL2
