/**
 * generated by Xtext 2.10.0
 */
package b2sql.b2SQL2;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>BType</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link b2sql.b2SQL2.BType#getType_name <em>Type name</em>}</li>
 * </ul>
 *
 * @see b2sql.b2SQL2.B2SQL2Package#getBType()
 * @model
 * @generated
 */
public interface BType extends EObject
{
  /**
   * Returns the value of the '<em><b>Type name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Type name</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Type name</em>' attribute.
   * @see #setType_name(String)
   * @see b2sql.b2SQL2.B2SQL2Package#getBType_Type_name()
   * @model
   * @generated
   */
  String getType_name();

  /**
   * Sets the value of the '{@link b2sql.b2SQL2.BType#getType_name <em>Type name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Type name</em>' attribute.
   * @see #getType_name()
   * @generated
   */
  void setType_name(String value);

} // BType
