/**
 * generated by Xtext 2.10.0
 */
package b2sql.b2SQL2;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Table Instance</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link b2sql.b2SQL2.TableInstance#getTi_name <em>Ti name</em>}</li>
 *   <li>{@link b2sql.b2SQL2.TableInstance#getTi_type <em>Ti type</em>}</li>
 * </ul>
 *
 * @see b2sql.b2SQL2.B2SQL2Package#getTableInstance()
 * @model
 * @generated
 */
public interface TableInstance extends EObject
{
  /**
   * Returns the value of the '<em><b>Ti name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Ti name</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Ti name</em>' attribute.
   * @see #setTi_name(String)
   * @see b2sql.b2SQL2.B2SQL2Package#getTableInstance_Ti_name()
   * @model
   * @generated
   */
  String getTi_name();

  /**
   * Sets the value of the '{@link b2sql.b2SQL2.TableInstance#getTi_name <em>Ti name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Ti name</em>' attribute.
   * @see #getTi_name()
   * @generated
   */
  void setTi_name(String value);

  /**
   * Returns the value of the '<em><b>Ti type</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Ti type</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Ti type</em>' containment reference.
   * @see #setTi_type(TIAssignment)
   * @see b2sql.b2SQL2.B2SQL2Package#getTableInstance_Ti_type()
   * @model containment="true"
   * @generated
   */
  TIAssignment getTi_type();

  /**
   * Sets the value of the '{@link b2sql.b2SQL2.TableInstance#getTi_type <em>Ti type</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Ti type</em>' containment reference.
   * @see #getTi_type()
   * @generated
   */
  void setTi_type(TIAssignment value);

} // TableInstance
