/**
 * generated by Xtext 2.10.0
 */
package bsqllog2java.validation;

import bsqllog2java.validation.AbstractBSQLLog2JavaValidator;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class BSQLLog2JavaValidator extends AbstractBSQLLog2JavaValidator {
}
