/**
 * generated by Xtext 2.10.0
 */
package bsql2java.validation;

import bsql2java.validation.AbstractBSQL2Java2Validator;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class BSQL2Java2Validator extends AbstractBSQL2Java2Validator {
}
