/*
 * generated by Xtext 2.10.0
 */
package bsql2java.ui.contentassist


/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
class BSQL2Java2ProposalProvider extends AbstractBSQL2Java2ProposalProvider {
}
