/**
 * generated by Xtext 2.10.0
 */
package secureuml2Java.secureUML2Java;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>BParameter</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link secureuml2Java.secureUML2Java.BParameter#getP_name <em>Pname</em>}</li>
 *   <li>{@link secureuml2Java.secureUML2Java.BParameter#getType <em>Type</em>}</li>
 * </ul>
 *
 * @see secureuml2Java.secureUML2Java.SecureUML2JavaPackage#getBParameter()
 * @model
 * @generated
 */
public interface BParameter extends EObject
{
  /**
   * Returns the value of the '<em><b>Pname</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Pname</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Pname</em>' attribute.
   * @see #setP_name(String)
   * @see secureuml2Java.secureUML2Java.SecureUML2JavaPackage#getBParameter_P_name()
   * @model
   * @generated
   */
  String getP_name();

  /**
   * Sets the value of the '{@link secureuml2Java.secureUML2Java.BParameter#getP_name <em>Pname</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Pname</em>' attribute.
   * @see #getP_name()
   * @generated
   */
  void setP_name(String value);

  /**
   * Returns the value of the '<em><b>Type</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Type</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Type</em>' containment reference.
   * @see #setType(BType)
   * @see secureuml2Java.secureUML2Java.SecureUML2JavaPackage#getBParameter_Type()
   * @model containment="true"
   * @generated
   */
  BType getType();

  /**
   * Sets the value of the '{@link secureuml2Java.secureUML2Java.BParameter#getType <em>Type</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Type</em>' containment reference.
   * @see #getType()
   * @generated
   */
  void setType(BType value);

} // BParameter
