/**
 * generated by Xtext 2.10.0
 */
package secureuml2Java.secureUML2Java;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>BPredicate</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link secureuml2Java.secureUML2Java.BPredicate#getPleft <em>Pleft</em>}</li>
 *   <li>{@link secureuml2Java.secureUML2Java.BPredicate#getPright <em>Pright</em>}</li>
 * </ul>
 *
 * @see secureuml2Java.secureUML2Java.SecureUML2JavaPackage#getBPredicate()
 * @model
 * @generated
 */
public interface BPredicate extends EObject
{
  /**
   * Returns the value of the '<em><b>Pleft</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Pleft</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Pleft</em>' containment reference.
   * @see #setPleft(EObject)
   * @see secureuml2Java.secureUML2Java.SecureUML2JavaPackage#getBPredicate_Pleft()
   * @model containment="true"
   * @generated
   */
  EObject getPleft();

  /**
   * Sets the value of the '{@link secureuml2Java.secureUML2Java.BPredicate#getPleft <em>Pleft</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Pleft</em>' containment reference.
   * @see #getPleft()
   * @generated
   */
  void setPleft(EObject value);

  /**
   * Returns the value of the '<em><b>Pright</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Pright</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Pright</em>' containment reference.
   * @see #setPright(EObject)
   * @see secureuml2Java.secureUML2Java.SecureUML2JavaPackage#getBPredicate_Pright()
   * @model containment="true"
   * @generated
   */
  EObject getPright();

  /**
   * Sets the value of the '{@link secureuml2Java.secureUML2Java.BPredicate#getPright <em>Pright</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Pright</em>' containment reference.
   * @see #getPright()
   * @generated
   */
  void setPright(EObject value);

} // BPredicate
