/**
 * generated by Xtext 2.10.0
 */
package secureuml2Java.secureUML2Java;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>BSees</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link secureuml2Java.secureUML2Java.BSees#getM_name <em>Mname</em>}</li>
 * </ul>
 *
 * @see secureuml2Java.secureUML2Java.SecureUML2JavaPackage#getBSees()
 * @model
 * @generated
 */
public interface BSees extends EObject
{
  /**
   * Returns the value of the '<em><b>Mname</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Mname</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Mname</em>' attribute.
   * @see #setM_name(String)
   * @see secureuml2Java.secureUML2Java.SecureUML2JavaPackage#getBSees_M_name()
   * @model
   * @generated
   */
  String getM_name();

  /**
   * Sets the value of the '{@link secureuml2Java.secureUML2Java.BSees#getM_name <em>Mname</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Mname</em>' attribute.
   * @see #getM_name()
   * @generated
   */
  void setM_name(String value);

} // BSees
