/**
 * generated by Xtext 2.10.0
 */
package secureuml2Java.secureUML2Java;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>BTuple</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link secureuml2Java.secureUML2Java.BTuple#getRan <em>Ran</em>}</li>
 *   <li>{@link secureuml2Java.secureUML2Java.BTuple#getDom <em>Dom</em>}</li>
 * </ul>
 *
 * @see secureuml2Java.secureUML2Java.SecureUML2JavaPackage#getBTuple()
 * @model
 * @generated
 */
public interface BTuple extends EObject
{
  /**
   * Returns the value of the '<em><b>Ran</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Ran</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Ran</em>' containment reference.
   * @see #setRan(EObject)
   * @see secureuml2Java.secureUML2Java.SecureUML2JavaPackage#getBTuple_Ran()
   * @model containment="true"
   * @generated
   */
  EObject getRan();

  /**
   * Sets the value of the '{@link secureuml2Java.secureUML2Java.BTuple#getRan <em>Ran</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Ran</em>' containment reference.
   * @see #getRan()
   * @generated
   */
  void setRan(EObject value);

  /**
   * Returns the value of the '<em><b>Dom</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Dom</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Dom</em>' attribute.
   * @see #setDom(String)
   * @see secureuml2Java.secureUML2Java.SecureUML2JavaPackage#getBTuple_Dom()
   * @model
   * @generated
   */
  String getDom();

  /**
   * Sets the value of the '{@link secureuml2Java.secureUML2Java.BTuple#getDom <em>Dom</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Dom</em>' attribute.
   * @see #getDom()
   * @generated
   */
  void setDom(String value);

} // BTuple
