/**
 * generated by Xtext 2.10.0
 */
package secureuml2SQL.tests;

import com.google.inject.Inject;
import org.eclipse.xtend2.lib.StringConcatenation;
import org.eclipse.xtext.junit4.InjectWith;
import org.eclipse.xtext.junit4.XtextRunner;
import org.eclipse.xtext.junit4.util.ParseHelper;
import org.eclipse.xtext.xbase.lib.Exceptions;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import secureuml2SQL.secureUML2SQL.SecureUML2SQL;
import secureuml2SQL.tests.SecureUML2SQLInjectorProvider;

@RunWith(XtextRunner.class)
@InjectWith(SecureUML2SQLInjectorProvider.class)
@SuppressWarnings("all")
public class SecureUML2SQLParsingTest {
  @Inject
  private ParseHelper<SecureUML2SQL> parseHelper;
  
  @Test
  public void loadModel() {
    try {
      StringConcatenation _builder = new StringConcatenation();
      _builder.append("Hello Xtext!");
      _builder.newLine();
      final SecureUML2SQL result = this.parseHelper.parse(_builder);
      Assert.assertNotNull(result);
    } catch (Throwable _e) {
      throw Exceptions.sneakyThrow(_e);
    }
  }
}
