/*
 * generated by Xtext 2.10.0
 */
package b2sql.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.validation.AbstractDeclarativeValidator;

public abstract class AbstractB2SQL2Validator extends AbstractDeclarativeValidator {
	
	@Override
	protected List<EPackage> getEPackages() {
		List<EPackage> result = new ArrayList<EPackage>();
		result.add(b2sql.b2SQL2.B2SQL2Package.eINSTANCE);
		return result;
	}
	
}
