/**
 * generated by Xtext 2.10.0
 */
package bsql2java.bSQL2Java.impl;

import bsql2java.bSQL2Java.*;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EPackage;

import org.eclipse.emf.ecore.impl.EFactoryImpl;

import org.eclipse.emf.ecore.plugin.EcorePlugin;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model <b>Factory</b>.
 * <!-- end-user-doc -->
 * @generated
 */
public class BSQL2JavaFactoryImpl extends EFactoryImpl implements BSQL2JavaFactory
{
  /**
   * Creates the default factory implementation.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public static BSQL2JavaFactory init()
  {
    try
    {
      BSQL2JavaFactory theBSQL2JavaFactory = (BSQL2JavaFactory)EPackage.Registry.INSTANCE.getEFactory(BSQL2JavaPackage.eNS_URI);
      if (theBSQL2JavaFactory != null)
      {
        return theBSQL2JavaFactory;
      }
    }
    catch (Exception exception)
    {
      EcorePlugin.INSTANCE.log(exception);
    }
    return new BSQL2JavaFactoryImpl();
  }

  /**
   * Creates an instance of the factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public BSQL2JavaFactoryImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EObject create(EClass eClass)
  {
    switch (eClass.getClassifierID())
    {
      case BSQL2JavaPackage.BSQL2_JAVA: return createBSQL2Java();
      case BSQL2JavaPackage.BSQL_MACHINE: return createBSQLMachine();
      case BSQL2JavaPackage.BTABLE: return createBTable();
      case BSQL2JavaPackage.ATTRIBUTE: return createAttribute();
      case BSQL2JavaPackage.BTYPE: return createBType();
      case BSQL2JavaPackage.BS_OPERATION: return createBSOperation();
      case BSQL2JavaPackage.BOOL_OPERATION: return createBoolOperation();
      case BSQL2JavaPackage.VOID_OPERATION: return createVoidOperation();
      case BSQL2JavaPackage.BPREDICATE: return createBPredicate();
      case BSQL2JavaPackage.SQL_CALL: return createSQLCall();
      case BSQL2JavaPackage.TABLE_INSTANCE: return createTableInstance();
      case BSQL2JavaPackage.TI_ASSIGNMENT: return createTIAssignment();
      case BSQL2JavaPackage.BPARAMETER: return createBParameter();
      case BSQL2JavaPackage.BSUBSTITUTION: return createBSubstitution();
      default:
        throw new IllegalArgumentException("The class '" + eClass.getName() + "' is not a valid classifier");
    }
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public BSQL2Java createBSQL2Java()
  {
    BSQL2JavaImpl bsql2Java = new BSQL2JavaImpl();
    return bsql2Java;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public BSQLMachine createBSQLMachine()
  {
    BSQLMachineImpl bsqlMachine = new BSQLMachineImpl();
    return bsqlMachine;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public BTable createBTable()
  {
    BTableImpl bTable = new BTableImpl();
    return bTable;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Attribute createAttribute()
  {
    AttributeImpl attribute = new AttributeImpl();
    return attribute;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public BType createBType()
  {
    BTypeImpl bType = new BTypeImpl();
    return bType;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public BSOperation createBSOperation()
  {
    BSOperationImpl bsOperation = new BSOperationImpl();
    return bsOperation;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public BoolOperation createBoolOperation()
  {
    BoolOperationImpl boolOperation = new BoolOperationImpl();
    return boolOperation;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public VoidOperation createVoidOperation()
  {
    VoidOperationImpl voidOperation = new VoidOperationImpl();
    return voidOperation;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public BPredicate createBPredicate()
  {
    BPredicateImpl bPredicate = new BPredicateImpl();
    return bPredicate;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public SQLCall createSQLCall()
  {
    SQLCallImpl sqlCall = new SQLCallImpl();
    return sqlCall;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public TableInstance createTableInstance()
  {
    TableInstanceImpl tableInstance = new TableInstanceImpl();
    return tableInstance;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public TIAssignment createTIAssignment()
  {
    TIAssignmentImpl tiAssignment = new TIAssignmentImpl();
    return tiAssignment;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public BParameter createBParameter()
  {
    BParameterImpl bParameter = new BParameterImpl();
    return bParameter;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public BSubstitution createBSubstitution()
  {
    BSubstitutionImpl bSubstitution = new BSubstitutionImpl();
    return bSubstitution;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public BSQL2JavaPackage getBSQL2JavaPackage()
  {
    return (BSQL2JavaPackage)getEPackage();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @deprecated
   * @generated
   */
  @Deprecated
  public static BSQL2JavaPackage getPackage()
  {
    return BSQL2JavaPackage.eINSTANCE;
  }

} //BSQL2JavaFactoryImpl
