/**
 * generated by Xtext 2.10.0
 */
package bsql2sql.ui;

import bsql2sql.ui.AbstractBSQL2SQLUiModule;
import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class BSQL2SQLUiModule extends AbstractBSQL2SQLUiModule {
  public BSQL2SQLUiModule(final AbstractUIPlugin plugin) {
    super(plugin);
  }
}
