/**
 * generated by Xtext 2.10.0
 */
package bsql2java.bSQL2Java2;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Attribute</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link bsql2java.bSQL2Java2.Attribute#getAtt_name <em>Att name</em>}</li>
 *   <li>{@link bsql2java.bSQL2Java2.Attribute#getType <em>Type</em>}</li>
 * </ul>
 *
 * @see bsql2java.bSQL2Java2.BSQL2Java2Package#getAttribute()
 * @model
 * @generated
 */
public interface Attribute extends EObject
{
  /**
   * Returns the value of the '<em><b>Att name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Att name</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Att name</em>' attribute.
   * @see #setAtt_name(String)
   * @see bsql2java.bSQL2Java2.BSQL2Java2Package#getAttribute_Att_name()
   * @model
   * @generated
   */
  String getAtt_name();

  /**
   * Sets the value of the '{@link bsql2java.bSQL2Java2.Attribute#getAtt_name <em>Att name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Att name</em>' attribute.
   * @see #getAtt_name()
   * @generated
   */
  void setAtt_name(String value);

  /**
   * Returns the value of the '<em><b>Type</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Type</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Type</em>' containment reference.
   * @see #setType(BType)
   * @see bsql2java.bSQL2Java2.BSQL2Java2Package#getAttribute_Type()
   * @model containment="true"
   * @generated
   */
  BType getType();

  /**
   * Sets the value of the '{@link bsql2java.bSQL2Java2.Attribute#getType <em>Type</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Type</em>' containment reference.
   * @see #getType()
   * @generated
   */
  void setType(BType value);

} // Attribute
