/**
 * generated by Xtext 2.10.0
 */
package bsql2java.bSQL2Java2;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>BElement</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link bsql2java.bSQL2Java2.BElement#getEname <em>Ename</em>}</li>
 * </ul>
 *
 * @see bsql2java.bSQL2Java2.BSQL2Java2Package#getBElement()
 * @model
 * @generated
 */
public interface BElement extends EObject
{
  /**
   * Returns the value of the '<em><b>Ename</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Ename</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Ename</em>' attribute.
   * @see #setEname(String)
   * @see bsql2java.bSQL2Java2.BSQL2Java2Package#getBElement_Ename()
   * @model
   * @generated
   */
  String getEname();

  /**
   * Sets the value of the '{@link bsql2java.bSQL2Java2.BElement#getEname <em>Ename</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Ename</em>' attribute.
   * @see #getEname()
   * @generated
   */
  void setEname(String value);

} // BElement
