/**
 * generated by Xtext 2.10.0
 */
package bsql2java.bSQL2Java2;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Void Operation</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link bsql2java.bSQL2Java2.VoidOperation#getOp_name <em>Op name</em>}</li>
 *   <li>{@link bsql2java.bSQL2Java2.VoidOperation#getPList <em>PList</em>}</li>
 *   <li>{@link bsql2java.bSQL2Java2.VoidOperation#getPTyping <em>PTyping</em>}</li>
 *   <li>{@link bsql2java.bSQL2Java2.VoidOperation#getSubs <em>Subs</em>}</li>
 * </ul>
 *
 * @see bsql2java.bSQL2Java2.BSQL2Java2Package#getVoidOperation()
 * @model
 * @generated
 */
public interface VoidOperation extends EObject
{
  /**
   * Returns the value of the '<em><b>Op name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Op name</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Op name</em>' attribute.
   * @see #setOp_name(String)
   * @see bsql2java.bSQL2Java2.BSQL2Java2Package#getVoidOperation_Op_name()
   * @model
   * @generated
   */
  String getOp_name();

  /**
   * Sets the value of the '{@link bsql2java.bSQL2Java2.VoidOperation#getOp_name <em>Op name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Op name</em>' attribute.
   * @see #getOp_name()
   * @generated
   */
  void setOp_name(String value);

  /**
   * Returns the value of the '<em><b>PList</b></em>' attribute list.
   * The list contents are of type {@link java.lang.String}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>PList</em>' attribute list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>PList</em>' attribute list.
   * @see bsql2java.bSQL2Java2.BSQL2Java2Package#getVoidOperation_PList()
   * @model unique="false"
   * @generated
   */
  EList<String> getPList();

  /**
   * Returns the value of the '<em><b>PTyping</b></em>' containment reference list.
   * The list contents are of type {@link bsql2java.bSQL2Java2.BParameterTyping}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>PTyping</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>PTyping</em>' containment reference list.
   * @see bsql2java.bSQL2Java2.BSQL2Java2Package#getVoidOperation_PTyping()
   * @model containment="true"
   * @generated
   */
  EList<BParameterTyping> getPTyping();

  /**
   * Returns the value of the '<em><b>Subs</b></em>' containment reference list.
   * The list contents are of type {@link bsql2java.bSQL2Java2.BSubstitution}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Subs</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Subs</em>' containment reference list.
   * @see bsql2java.bSQL2Java2.BSQL2Java2Package#getVoidOperation_Subs()
   * @model containment="true"
   * @generated
   */
  EList<BSubstitution> getSubs();

} // VoidOperation
