/**
 * generated by Xtext 2.10.0
 */
package bsqllog2java.tests;

import bsqllog2java.bSQLLog2Java.BSQLLog2Java;
import bsqllog2java.tests.BSQLLog2JavaInjectorProvider;
import com.google.inject.Inject;
import org.eclipse.xtend2.lib.StringConcatenation;
import org.eclipse.xtext.junit4.InjectWith;
import org.eclipse.xtext.junit4.XtextRunner;
import org.eclipse.xtext.junit4.util.ParseHelper;
import org.eclipse.xtext.xbase.lib.Exceptions;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;

@RunWith(XtextRunner.class)
@InjectWith(BSQLLog2JavaInjectorProvider.class)
@SuppressWarnings("all")
public class BSQLLog2JavaParsingTest {
  @Inject
  private ParseHelper<BSQLLog2Java> parseHelper;
  
  @Test
  public void loadModel() {
    try {
      StringConcatenation _builder = new StringConcatenation();
      _builder.append("Hello Xtext!");
      _builder.newLine();
      final BSQLLog2Java result = this.parseHelper.parse(_builder);
      Assert.assertNotNull(result);
    } catch (Throwable _e) {
      throw Exceptions.sneakyThrow(_e);
    }
  }
}
