/*
 * generated by Xtext 2.10.0
 */
package bsqllog2java.ide.contentassist.antlr;

import bsqllog2java.ide.contentassist.antlr.internal.InternalBSQLLog2JavaParser;
import bsqllog2java.services.BSQLLog2JavaGrammarAccess;
import com.google.inject.Inject;
import java.util.Collection;
import java.util.HashMap;
import java.util.Map;
import org.antlr.runtime.RecognitionException;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ide.editor.contentassist.antlr.AbstractContentAssistParser;
import org.eclipse.xtext.ide.editor.contentassist.antlr.FollowElement;
import org.eclipse.xtext.ide.editor.contentassist.antlr.internal.AbstractInternalContentAssistParser;

public class BSQLLog2JavaParser extends AbstractContentAssistParser {

	@Inject
	private BSQLLog2JavaGrammarAccess grammarAccess;

	private Map<AbstractElement, String> nameMappings;

	@Override
	protected InternalBSQLLog2JavaParser createParser() {
		InternalBSQLLog2JavaParser result = new InternalBSQLLog2JavaParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}

	@Override
	protected String getRuleName(AbstractElement element) {
		if (nameMappings == null) {
			nameMappings = new HashMap<AbstractElement, String>() {
				private static final long serialVersionUID = 1L;
				{
					put(grammarAccess.getBOperationAccess().getAlternatives(), "rule__BOperation__Alternatives");
					put(grammarAccess.getBValueAccess().getAlternatives(), "rule__BValue__Alternatives");
					put(grammarAccess.getBoolOperationAccess().getAlternatives_10(), "rule__BoolOperation__Alternatives_10");
					put(grammarAccess.getBSubstitutionAccess().getAlternatives_2(), "rule__BSubstitution__Alternatives_2");
					put(grammarAccess.getBUnionAccess().getAlternatives_2(), "rule__BUnion__Alternatives_2");
					put(grammarAccess.getBSQLMachineAccess().getGroup(), "rule__BSQLMachine__Group__0");
					put(grammarAccess.getBSQLMachineAccess().getGroup_2(), "rule__BSQLMachine__Group_2__0");
					put(grammarAccess.getBSQLMachineAccess().getGroup_2_2(), "rule__BSQLMachine__Group_2_2__0");
					put(grammarAccess.getBSQLMachineAccess().getGroup_13(), "rule__BSQLMachine__Group_13__0");
					put(grammarAccess.getBTableAccess().getGroup(), "rule__BTable__Group__0");
					put(grammarAccess.getBTableAccess().getGroup_5(), "rule__BTable__Group_5__0");
					put(grammarAccess.getAttributeAccess().getGroup(), "rule__Attribute__Group__0");
					put(grammarAccess.getBoolOperationAccess().getGroup(), "rule__BoolOperation__Group__0");
					put(grammarAccess.getBoolOperationAccess().getGroup_4(), "rule__BoolOperation__Group_4__0");
					put(grammarAccess.getBoolOperationAccess().getGroup_4_1(), "rule__BoolOperation__Group_4_1__0");
					put(grammarAccess.getBoolOperationAccess().getGroup_8(), "rule__BoolOperation__Group_8__0");
					put(grammarAccess.getBoolOperationAccess().getGroup_8_1(), "rule__BoolOperation__Group_8_1__0");
					put(grammarAccess.getBSubTrueAccess().getGroup(), "rule__BSubTrue__Group__0");
					put(grammarAccess.getBSubTrueAccess().getGroup_7(), "rule__BSubTrue__Group_7__0");
					put(grammarAccess.getBSubFalseAccess().getGroup(), "rule__BSubFalse__Group__0");
					put(grammarAccess.getBSubFalseAccess().getGroup_9(), "rule__BSubFalse__Group_9__0");
					put(grammarAccess.getStringOperationAccess().getGroup(), "rule__StringOperation__Group__0");
					put(grammarAccess.getStringOperationAccess().getGroup_4(), "rule__StringOperation__Group_4__0");
					put(grammarAccess.getStringOperationAccess().getGroup_4_1(), "rule__StringOperation__Group_4_1__0");
					put(grammarAccess.getStringOperationAccess().getGroup_8(), "rule__StringOperation__Group_8__0");
					put(grammarAccess.getStringOperationAccess().getGroup_8_1(), "rule__StringOperation__Group_8_1__0");
					put(grammarAccess.getBAnyBlockAccess().getGroup(), "rule__BAnyBlock__Group__0");
					put(grammarAccess.getBAnyBlockAccess().getGroup_1(), "rule__BAnyBlock__Group_1__0");
					put(grammarAccess.getBAnyBlockAccess().getGroup_1_1(), "rule__BAnyBlock__Group_1_1__0");
					put(grammarAccess.getBAnyBlockAccess().getGroup_3(), "rule__BAnyBlock__Group_3__0");
					put(grammarAccess.getBAnyBlockAccess().getGroup_3_1(), "rule__BAnyBlock__Group_3_1__0");
					put(grammarAccess.getBAnyBlockAccess().getGroup_6(), "rule__BAnyBlock__Group_6__0");
					put(grammarAccess.getBAnyBlockAccess().getGroup_8(), "rule__BAnyBlock__Group_8__0");
					put(grammarAccess.getBAnyBlockAccess().getGroup_8_1(), "rule__BAnyBlock__Group_8_1__0");
					put(grammarAccess.getVoidOperationAccess().getGroup(), "rule__VoidOperation__Group__0");
					put(grammarAccess.getVoidOperationAccess().getGroup_2(), "rule__VoidOperation__Group_2__0");
					put(grammarAccess.getVoidOperationAccess().getGroup_2_1(), "rule__VoidOperation__Group_2_1__0");
					put(grammarAccess.getVoidOperationAccess().getGroup_6(), "rule__VoidOperation__Group_6__0");
					put(grammarAccess.getVoidOperationAccess().getGroup_6_1(), "rule__VoidOperation__Group_6_1__0");
					put(grammarAccess.getVoidOperationAccess().getGroup_9(), "rule__VoidOperation__Group_9__0");
					put(grammarAccess.getBPredicateAccess().getGroup(), "rule__BPredicate__Group__0");
					put(grammarAccess.getBPredicateAccess().getGroup_1(), "rule__BPredicate__Group_1__0");
					put(grammarAccess.getSQLCallAccess().getGroup(), "rule__SQLCall__Group__0");
					put(grammarAccess.getTableInstanceAccess().getGroup(), "rule__TableInstance__Group__0");
					put(grammarAccess.getTIAssignmentAccess().getGroup(), "rule__TIAssignment__Group__0");
					put(grammarAccess.getBParameterTypingAccess().getGroup(), "rule__BParameterTyping__Group__0");
					put(grammarAccess.getBSubstitutionAccess().getGroup(), "rule__BSubstitution__Group__0");
					put(grammarAccess.getBUnionAccess().getGroup(), "rule__BUnion__Group__0");
					put(grammarAccess.getBElementStructureAccess().getGroup(), "rule__BElementStructure__Group__0");
					put(grammarAccess.getBElementStructureAccess().getGroup_3(), "rule__BElementStructure__Group_3__0");
					put(grammarAccess.getBSQLMachineAccess().getM_nameAssignment_1(), "rule__BSQLMachine__M_nameAssignment_1");
					put(grammarAccess.getBSQLMachineAccess().getSeenameAssignment_2_1(), "rule__BSQLMachine__SeenameAssignment_2_1");
					put(grammarAccess.getBSQLMachineAccess().getSeenameAssignment_2_2_1(), "rule__BSQLMachine__SeenameAssignment_2_2_1");
					put(grammarAccess.getBSQLMachineAccess().getVarsAssignment_4(), "rule__BSQLMachine__VarsAssignment_4");
					put(grammarAccess.getBSQLMachineAccess().getInvAssignment_6(), "rule__BSQLMachine__InvAssignment_6");
					put(grammarAccess.getBSQLMachineAccess().getInitAssignment_8(), "rule__BSQLMachine__InitAssignment_8");
					put(grammarAccess.getBSQLMachineAccess().getBopsAssignment_12(), "rule__BSQLMachine__BopsAssignment_12");
					put(grammarAccess.getBSQLMachineAccess().getBopsAssignment_13_1(), "rule__BSQLMachine__BopsAssignment_13_1");
					put(grammarAccess.getBOperationAccess().getBopsAssignment_0(), "rule__BOperation__BopsAssignment_0");
					put(grammarAccess.getBOperationAccess().getVopsAssignment_1(), "rule__BOperation__VopsAssignment_1");
					put(grammarAccess.getBOperationAccess().getSopsAssignment_2(), "rule__BOperation__SopsAssignment_2");
					put(grammarAccess.getBTableAccess().getTable_nameAssignment_0(), "rule__BTable__Table_nameAssignment_0");
					put(grammarAccess.getBTableAccess().getAttributesAssignment_4(), "rule__BTable__AttributesAssignment_4");
					put(grammarAccess.getBTableAccess().getAttributesAssignment_5_1(), "rule__BTable__AttributesAssignment_5_1");
					put(grammarAccess.getAttributeAccess().getAtt_nameAssignment_0(), "rule__Attribute__Att_nameAssignment_0");
					put(grammarAccess.getAttributeAccess().getTypeAssignment_2(), "rule__Attribute__TypeAssignment_2");
					put(grammarAccess.getBTypeAccess().getType_nameAssignment(), "rule__BType__Type_nameAssignment");
					put(grammarAccess.getBoolOperationAccess().getResAssignment_0(), "rule__BoolOperation__ResAssignment_0");
					put(grammarAccess.getBoolOperationAccess().getOp_nameAssignment_2(), "rule__BoolOperation__Op_nameAssignment_2");
					put(grammarAccess.getBoolOperationAccess().getPListAssignment_4_0(), "rule__BoolOperation__PListAssignment_4_0");
					put(grammarAccess.getBoolOperationAccess().getPListAssignment_4_1_1(), "rule__BoolOperation__PListAssignment_4_1_1");
					put(grammarAccess.getBoolOperationAccess().getPTypingAssignment_8_0(), "rule__BoolOperation__PTypingAssignment_8_0");
					put(grammarAccess.getBoolOperationAccess().getPTypingAssignment_8_1_1(), "rule__BoolOperation__PTypingAssignment_8_1_1");
					put(grammarAccess.getBoolOperationAccess().getReshasAssignment_10_0(), "rule__BoolOperation__ReshasAssignment_10_0");
					put(grammarAccess.getBoolOperationAccess().getResnoAssignment_10_1(), "rule__BoolOperation__ResnoAssignment_10_1");
					put(grammarAccess.getBSubTrueAccess().getResAssignment_0(), "rule__BSubTrue__ResAssignment_0");
					put(grammarAccess.getBSubTrueAccess().getObjTableAssignment_4(), "rule__BSubTrue__ObjTableAssignment_4");
					put(grammarAccess.getBSubTrueAccess().getPresAssignment_6(), "rule__BSubTrue__PresAssignment_6");
					put(grammarAccess.getBSubTrueAccess().getPresAssignment_7_1(), "rule__BSubTrue__PresAssignment_7_1");
					put(grammarAccess.getBSubFalseAccess().getResAssignment_0(), "rule__BSubFalse__ResAssignment_0");
					put(grammarAccess.getBSubFalseAccess().getObjTableAssignment_6(), "rule__BSubFalse__ObjTableAssignment_6");
					put(grammarAccess.getBSubFalseAccess().getPresAssignment_8(), "rule__BSubFalse__PresAssignment_8");
					put(grammarAccess.getBSubFalseAccess().getPresAssignment_9_1(), "rule__BSubFalse__PresAssignment_9_1");
					put(grammarAccess.getStringOperationAccess().getResAssignment_0(), "rule__StringOperation__ResAssignment_0");
					put(grammarAccess.getStringOperationAccess().getOp_nameAssignment_2(), "rule__StringOperation__Op_nameAssignment_2");
					put(grammarAccess.getStringOperationAccess().getPListAssignment_4_0(), "rule__StringOperation__PListAssignment_4_0");
					put(grammarAccess.getStringOperationAccess().getPListAssignment_4_1_1(), "rule__StringOperation__PListAssignment_4_1_1");
					put(grammarAccess.getStringOperationAccess().getPTypingAssignment_8_0(), "rule__StringOperation__PTypingAssignment_8_0");
					put(grammarAccess.getStringOperationAccess().getPTypingAssignment_8_1_1(), "rule__StringOperation__PTypingAssignment_8_1_1");
					put(grammarAccess.getStringOperationAccess().getAnyblockAssignment_10(), "rule__StringOperation__AnyblockAssignment_10");
					put(grammarAccess.getBAnyBlockAccess().getVarListAssignment_1_0(), "rule__BAnyBlock__VarListAssignment_1_0");
					put(grammarAccess.getBAnyBlockAccess().getVarListAssignment_1_1_1(), "rule__BAnyBlock__VarListAssignment_1_1_1");
					put(grammarAccess.getBAnyBlockAccess().getVarTypingAssignment_3_0(), "rule__BAnyBlock__VarTypingAssignment_3_0");
					put(grammarAccess.getBAnyBlockAccess().getVarTypingAssignment_3_1_1(), "rule__BAnyBlock__VarTypingAssignment_3_1_1");
					put(grammarAccess.getBAnyBlockAccess().getPresAssignment_5(), "rule__BAnyBlock__PresAssignment_5");
					put(grammarAccess.getBAnyBlockAccess().getPresAssignment_6_1(), "rule__BAnyBlock__PresAssignment_6_1");
					put(grammarAccess.getBAnyBlockAccess().getSubsAssignment_8_0(), "rule__BAnyBlock__SubsAssignment_8_0");
					put(grammarAccess.getBAnyBlockAccess().getSubsAssignment_8_1_1(), "rule__BAnyBlock__SubsAssignment_8_1_1");
					put(grammarAccess.getVoidOperationAccess().getOp_nameAssignment_0(), "rule__VoidOperation__Op_nameAssignment_0");
					put(grammarAccess.getVoidOperationAccess().getPListAssignment_2_0(), "rule__VoidOperation__PListAssignment_2_0");
					put(grammarAccess.getVoidOperationAccess().getPListAssignment_2_1_1(), "rule__VoidOperation__PListAssignment_2_1_1");
					put(grammarAccess.getVoidOperationAccess().getPTypingAssignment_6_0(), "rule__VoidOperation__PTypingAssignment_6_0");
					put(grammarAccess.getVoidOperationAccess().getPTypingAssignment_6_1_1(), "rule__VoidOperation__PTypingAssignment_6_1_1");
					put(grammarAccess.getVoidOperationAccess().getSubsAssignment_8(), "rule__VoidOperation__SubsAssignment_8");
					put(grammarAccess.getVoidOperationAccess().getSubsAssignment_9_1(), "rule__VoidOperation__SubsAssignment_9_1");
					put(grammarAccess.getBPredicateAccess().getPLeftAssignment_1_0(), "rule__BPredicate__PLeftAssignment_1_0");
					put(grammarAccess.getBPredicateAccess().getPRightAssignment_1_2(), "rule__BPredicate__PRightAssignment_1_2");
					put(grammarAccess.getSQLCallAccess().getSLeftAssignment_0(), "rule__SQLCall__SLeftAssignment_0");
					put(grammarAccess.getSQLCallAccess().getSRightAssignment_2(), "rule__SQLCall__SRightAssignment_2");
					put(grammarAccess.getTableInstanceAccess().getTi_nameAssignment_0(), "rule__TableInstance__Ti_nameAssignment_0");
					put(grammarAccess.getTableInstanceAccess().getTi_typeAssignment_2(), "rule__TableInstance__Ti_typeAssignment_2");
					put(grammarAccess.getTIAssignmentAccess().getInstance_nameAssignment_0(), "rule__TIAssignment__Instance_nameAssignment_0");
					put(grammarAccess.getTIAssignmentAccess().getInstance_typeAssignment_2(), "rule__TIAssignment__Instance_typeAssignment_2");
					put(grammarAccess.getBParameterTypingAccess().getP_nameAssignment_0(), "rule__BParameterTyping__P_nameAssignment_0");
					put(grammarAccess.getBParameterTypingAccess().getTypeAssignment_2(), "rule__BParameterTyping__TypeAssignment_2");
					put(grammarAccess.getBSubstitutionAccess().getLeftAssignment_0(), "rule__BSubstitution__LeftAssignment_0");
					put(grammarAccess.getBSubstitutionAccess().getPrightAssignment_2_0(), "rule__BSubstitution__PrightAssignment_2_0");
					put(grammarAccess.getBSubstitutionAccess().getUrightAssignment_2_1(), "rule__BSubstitution__UrightAssignment_2_1");
					put(grammarAccess.getBSubstitutionAccess().getSrightAssignment_2_2(), "rule__BSubstitution__SrightAssignment_2_2");
					put(grammarAccess.getBUnionAccess().getSetAssignment_0(), "rule__BUnion__SetAssignment_0");
					put(grammarAccess.getBUnionAccess().getAddedSetAssignment_2_0(), "rule__BUnion__AddedSetAssignment_2_0");
					put(grammarAccess.getBUnionAccess().getAddedEAssignment_2_1(), "rule__BUnion__AddedEAssignment_2_1");
					put(grammarAccess.getBElementStructureAccess().getEAssignment_2(), "rule__BElementStructure__EAssignment_2");
					put(grammarAccess.getBElementStructureAccess().getEAssignment_3_1(), "rule__BElementStructure__EAssignment_3_1");
					put(grammarAccess.getBElementAccess().getEnameAssignment(), "rule__BElement__EnameAssignment");
					put(grammarAccess.getBSetAccess().getSet_nameAssignment(), "rule__BSet__Set_nameAssignment");
				}
			};
		}
		return nameMappings.get(element);
	}

	@Override
	protected Collection<FollowElement> getFollowElements(AbstractInternalContentAssistParser parser) {
		try {
			InternalBSQLLog2JavaParser typedParser = (InternalBSQLLog2JavaParser) parser;
			typedParser.entryRuleBSQLLog2Java();
			return typedParser.getFollowElements();
		} catch(RecognitionException ex) {
			throw new RuntimeException(ex);
		}
	}

	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}

	public BSQLLog2JavaGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(BSQLLog2JavaGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
