/**
 * generated by Xtext 2.10.0
 */
package bsql2sql.ui.contentassist;

import bsql2sql.ui.contentassist.AbstractBSQL2SQLProposalProvider;

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
@SuppressWarnings("all")
public class BSQL2SQLProposalProvider extends AbstractBSQL2SQLProposalProvider {
}
