/**
 * generated by Xtext 2.10.0
 */
package bsql2sql.bSQL2SQL;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see bsql2sql.bSQL2SQL.BSQL2SQLFactory
 * @model kind="package"
 * @generated
 */
public interface BSQL2SQLPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "bSQL2SQL";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.BSQL2SQL.bsql2sql";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "bSQL2SQL";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  BSQL2SQLPackage eINSTANCE = bsql2sql.bSQL2SQL.impl.BSQL2SQLPackageImpl.init();

  /**
   * The meta object id for the '{@link bsql2sql.bSQL2SQL.impl.BSQL2SQLImpl <em>BSQL2SQL</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see bsql2sql.bSQL2SQL.impl.BSQL2SQLImpl
   * @see bsql2sql.bSQL2SQL.impl.BSQL2SQLPackageImpl#getBSQL2SQL()
   * @generated
   */
  int BSQL2SQL = 0;

  /**
   * The number of structural features of the '<em>BSQL2SQL</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BSQL2SQL_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link bsql2sql.bSQL2SQL.impl.BSQLMachineImpl <em>BSQL Machine</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see bsql2sql.bSQL2SQL.impl.BSQLMachineImpl
   * @see bsql2sql.bSQL2SQL.impl.BSQL2SQLPackageImpl#getBSQLMachine()
   * @generated
   */
  int BSQL_MACHINE = 1;

  /**
   * The feature id for the '<em><b>Mname</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BSQL_MACHINE__MNAME = BSQL2SQL_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Vars</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BSQL_MACHINE__VARS = BSQL2SQL_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Inv</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BSQL_MACHINE__INV = BSQL2SQL_FEATURE_COUNT + 2;

  /**
   * The feature id for the '<em><b>Init</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BSQL_MACHINE__INIT = BSQL2SQL_FEATURE_COUNT + 3;

  /**
   * The feature id for the '<em><b>Ops</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BSQL_MACHINE__OPS = BSQL2SQL_FEATURE_COUNT + 4;

  /**
   * The number of structural features of the '<em>BSQL Machine</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BSQL_MACHINE_FEATURE_COUNT = BSQL2SQL_FEATURE_COUNT + 5;

  /**
   * The meta object id for the '{@link bsql2sql.bSQL2SQL.impl.BTableImpl <em>BTable</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see bsql2sql.bSQL2SQL.impl.BTableImpl
   * @see bsql2sql.bSQL2SQL.impl.BSQL2SQLPackageImpl#getBTable()
   * @generated
   */
  int BTABLE = 2;

  /**
   * The feature id for the '<em><b>Table name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BTABLE__TABLE_NAME = 0;

  /**
   * The feature id for the '<em><b>Attributes</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BTABLE__ATTRIBUTES = 1;

  /**
   * The number of structural features of the '<em>BTable</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BTABLE_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link bsql2sql.bSQL2SQL.impl.AttributeImpl <em>Attribute</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see bsql2sql.bSQL2SQL.impl.AttributeImpl
   * @see bsql2sql.bSQL2SQL.impl.BSQL2SQLPackageImpl#getAttribute()
   * @generated
   */
  int ATTRIBUTE = 3;

  /**
   * The feature id for the '<em><b>Att name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ATTRIBUTE__ATT_NAME = 0;

  /**
   * The feature id for the '<em><b>Type</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ATTRIBUTE__TYPE = 1;

  /**
   * The number of structural features of the '<em>Attribute</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ATTRIBUTE_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link bsql2sql.bSQL2SQL.impl.BTypeImpl <em>BType</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see bsql2sql.bSQL2SQL.impl.BTypeImpl
   * @see bsql2sql.bSQL2SQL.impl.BSQL2SQLPackageImpl#getBType()
   * @generated
   */
  int BTYPE = 4;

  /**
   * The feature id for the '<em><b>Type name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BTYPE__TYPE_NAME = 0;

  /**
   * The number of structural features of the '<em>BType</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BTYPE_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link bsql2sql.bSQL2SQL.impl.BSOperationImpl <em>BS Operation</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see bsql2sql.bSQL2SQL.impl.BSOperationImpl
   * @see bsql2sql.bSQL2SQL.impl.BSQL2SQLPackageImpl#getBSOperation()
   * @generated
   */
  int BS_OPERATION = 5;

  /**
   * The feature id for the '<em><b>Bop</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BS_OPERATION__BOP = 0;

  /**
   * The feature id for the '<em><b>Vop</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BS_OPERATION__VOP = 1;

  /**
   * The number of structural features of the '<em>BS Operation</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BS_OPERATION_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link bsql2sql.bSQL2SQL.impl.BoolOperationImpl <em>Bool Operation</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see bsql2sql.bSQL2SQL.impl.BoolOperationImpl
   * @see bsql2sql.bSQL2SQL.impl.BSQL2SQLPackageImpl#getBoolOperation()
   * @generated
   */
  int BOOL_OPERATION = 6;

  /**
   * The feature id for the '<em><b>Op name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BOOL_OPERATION__OP_NAME = 0;

  /**
   * The feature id for the '<em><b>PList</b></em>' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BOOL_OPERATION__PLIST = 1;

  /**
   * The feature id for the '<em><b>Params</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BOOL_OPERATION__PARAMS = 2;

  /**
   * The feature id for the '<em><b>Obj Table</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BOOL_OPERATION__OBJ_TABLE = 3;

  /**
   * The feature id for the '<em><b>Pres</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BOOL_OPERATION__PRES = 4;

  /**
   * The number of structural features of the '<em>Bool Operation</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BOOL_OPERATION_FEATURE_COUNT = 5;

  /**
   * The meta object id for the '{@link bsql2sql.bSQL2SQL.impl.VoidOperationImpl <em>Void Operation</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see bsql2sql.bSQL2SQL.impl.VoidOperationImpl
   * @see bsql2sql.bSQL2SQL.impl.BSQL2SQLPackageImpl#getVoidOperation()
   * @generated
   */
  int VOID_OPERATION = 7;

  /**
   * The feature id for the '<em><b>Op name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VOID_OPERATION__OP_NAME = 0;

  /**
   * The feature id for the '<em><b>PList</b></em>' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VOID_OPERATION__PLIST = 1;

  /**
   * The feature id for the '<em><b>Params</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VOID_OPERATION__PARAMS = 2;

  /**
   * The feature id for the '<em><b>Subs</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VOID_OPERATION__SUBS = 3;

  /**
   * The number of structural features of the '<em>Void Operation</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VOID_OPERATION_FEATURE_COUNT = 4;

  /**
   * The meta object id for the '{@link bsql2sql.bSQL2SQL.impl.BPredicateImpl <em>BPredicate</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see bsql2sql.bSQL2SQL.impl.BPredicateImpl
   * @see bsql2sql.bSQL2SQL.impl.BSQL2SQLPackageImpl#getBPredicate()
   * @generated
   */
  int BPREDICATE = 8;

  /**
   * The feature id for the '<em><b>PLeft</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BPREDICATE__PLEFT = 0;

  /**
   * The feature id for the '<em><b>PRight</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BPREDICATE__PRIGHT = 1;

  /**
   * The number of structural features of the '<em>BPredicate</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BPREDICATE_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link bsql2sql.bSQL2SQL.impl.SQLCallImpl <em>SQL Call</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see bsql2sql.bSQL2SQL.impl.SQLCallImpl
   * @see bsql2sql.bSQL2SQL.impl.BSQL2SQLPackageImpl#getSQLCall()
   * @generated
   */
  int SQL_CALL = 9;

  /**
   * The feature id for the '<em><b>SLeft</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SQL_CALL__SLEFT = 0;

  /**
   * The feature id for the '<em><b>SRight</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SQL_CALL__SRIGHT = 1;

  /**
   * The number of structural features of the '<em>SQL Call</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SQL_CALL_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link bsql2sql.bSQL2SQL.impl.TableInstanceImpl <em>Table Instance</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see bsql2sql.bSQL2SQL.impl.TableInstanceImpl
   * @see bsql2sql.bSQL2SQL.impl.BSQL2SQLPackageImpl#getTableInstance()
   * @generated
   */
  int TABLE_INSTANCE = 10;

  /**
   * The feature id for the '<em><b>Ti name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TABLE_INSTANCE__TI_NAME = 0;

  /**
   * The feature id for the '<em><b>Ti type</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TABLE_INSTANCE__TI_TYPE = 1;

  /**
   * The number of structural features of the '<em>Table Instance</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TABLE_INSTANCE_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link bsql2sql.bSQL2SQL.impl.TIAssignmentImpl <em>TI Assignment</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see bsql2sql.bSQL2SQL.impl.TIAssignmentImpl
   * @see bsql2sql.bSQL2SQL.impl.BSQL2SQLPackageImpl#getTIAssignment()
   * @generated
   */
  int TI_ASSIGNMENT = 11;

  /**
   * The feature id for the '<em><b>Instance name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TI_ASSIGNMENT__INSTANCE_NAME = 0;

  /**
   * The feature id for the '<em><b>Instance type</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TI_ASSIGNMENT__INSTANCE_TYPE = 1;

  /**
   * The number of structural features of the '<em>TI Assignment</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TI_ASSIGNMENT_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link bsql2sql.bSQL2SQL.impl.BParameterImpl <em>BParameter</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see bsql2sql.bSQL2SQL.impl.BParameterImpl
   * @see bsql2sql.bSQL2SQL.impl.BSQL2SQLPackageImpl#getBParameter()
   * @generated
   */
  int BPARAMETER = 12;

  /**
   * The feature id for the '<em><b>Pname</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BPARAMETER__PNAME = 0;

  /**
   * The feature id for the '<em><b>Type</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BPARAMETER__TYPE = 1;

  /**
   * The number of structural features of the '<em>BParameter</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BPARAMETER_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link bsql2sql.bSQL2SQL.impl.BSubstitutionImpl <em>BSubstitution</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see bsql2sql.bSQL2SQL.impl.BSubstitutionImpl
   * @see bsql2sql.bSQL2SQL.impl.BSQL2SQLPackageImpl#getBSubstitution()
   * @generated
   */
  int BSUBSTITUTION = 13;

  /**
   * The feature id for the '<em><b>Left</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BSUBSTITUTION__LEFT = 0;

  /**
   * The feature id for the '<em><b>Right</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BSUBSTITUTION__RIGHT = 1;

  /**
   * The number of structural features of the '<em>BSubstitution</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BSUBSTITUTION_FEATURE_COUNT = 2;


  /**
   * Returns the meta object for class '{@link bsql2sql.bSQL2SQL.BSQL2SQL <em>BSQL2SQL</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>BSQL2SQL</em>'.
   * @see bsql2sql.bSQL2SQL.BSQL2SQL
   * @generated
   */
  EClass getBSQL2SQL();

  /**
   * Returns the meta object for class '{@link bsql2sql.bSQL2SQL.BSQLMachine <em>BSQL Machine</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>BSQL Machine</em>'.
   * @see bsql2sql.bSQL2SQL.BSQLMachine
   * @generated
   */
  EClass getBSQLMachine();

  /**
   * Returns the meta object for the attribute '{@link bsql2sql.bSQL2SQL.BSQLMachine#getM_name <em>Mname</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Mname</em>'.
   * @see bsql2sql.bSQL2SQL.BSQLMachine#getM_name()
   * @see #getBSQLMachine()
   * @generated
   */
  EAttribute getBSQLMachine_M_name();

  /**
   * Returns the meta object for the attribute '{@link bsql2sql.bSQL2SQL.BSQLMachine#getVars <em>Vars</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Vars</em>'.
   * @see bsql2sql.bSQL2SQL.BSQLMachine#getVars()
   * @see #getBSQLMachine()
   * @generated
   */
  EAttribute getBSQLMachine_Vars();

  /**
   * Returns the meta object for the containment reference '{@link bsql2sql.bSQL2SQL.BSQLMachine#getInv <em>Inv</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Inv</em>'.
   * @see bsql2sql.bSQL2SQL.BSQLMachine#getInv()
   * @see #getBSQLMachine()
   * @generated
   */
  EReference getBSQLMachine_Inv();

  /**
   * Returns the meta object for the attribute '{@link bsql2sql.bSQL2SQL.BSQLMachine#getInit <em>Init</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Init</em>'.
   * @see bsql2sql.bSQL2SQL.BSQLMachine#getInit()
   * @see #getBSQLMachine()
   * @generated
   */
  EAttribute getBSQLMachine_Init();

  /**
   * Returns the meta object for the containment reference list '{@link bsql2sql.bSQL2SQL.BSQLMachine#getOps <em>Ops</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Ops</em>'.
   * @see bsql2sql.bSQL2SQL.BSQLMachine#getOps()
   * @see #getBSQLMachine()
   * @generated
   */
  EReference getBSQLMachine_Ops();

  /**
   * Returns the meta object for class '{@link bsql2sql.bSQL2SQL.BTable <em>BTable</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>BTable</em>'.
   * @see bsql2sql.bSQL2SQL.BTable
   * @generated
   */
  EClass getBTable();

  /**
   * Returns the meta object for the attribute '{@link bsql2sql.bSQL2SQL.BTable#getTable_name <em>Table name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Table name</em>'.
   * @see bsql2sql.bSQL2SQL.BTable#getTable_name()
   * @see #getBTable()
   * @generated
   */
  EAttribute getBTable_Table_name();

  /**
   * Returns the meta object for the containment reference list '{@link bsql2sql.bSQL2SQL.BTable#getAttributes <em>Attributes</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Attributes</em>'.
   * @see bsql2sql.bSQL2SQL.BTable#getAttributes()
   * @see #getBTable()
   * @generated
   */
  EReference getBTable_Attributes();

  /**
   * Returns the meta object for class '{@link bsql2sql.bSQL2SQL.Attribute <em>Attribute</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Attribute</em>'.
   * @see bsql2sql.bSQL2SQL.Attribute
   * @generated
   */
  EClass getAttribute();

  /**
   * Returns the meta object for the attribute '{@link bsql2sql.bSQL2SQL.Attribute#getAtt_name <em>Att name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Att name</em>'.
   * @see bsql2sql.bSQL2SQL.Attribute#getAtt_name()
   * @see #getAttribute()
   * @generated
   */
  EAttribute getAttribute_Att_name();

  /**
   * Returns the meta object for the containment reference '{@link bsql2sql.bSQL2SQL.Attribute#getType <em>Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Type</em>'.
   * @see bsql2sql.bSQL2SQL.Attribute#getType()
   * @see #getAttribute()
   * @generated
   */
  EReference getAttribute_Type();

  /**
   * Returns the meta object for class '{@link bsql2sql.bSQL2SQL.BType <em>BType</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>BType</em>'.
   * @see bsql2sql.bSQL2SQL.BType
   * @generated
   */
  EClass getBType();

  /**
   * Returns the meta object for the attribute '{@link bsql2sql.bSQL2SQL.BType#getType_name <em>Type name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Type name</em>'.
   * @see bsql2sql.bSQL2SQL.BType#getType_name()
   * @see #getBType()
   * @generated
   */
  EAttribute getBType_Type_name();

  /**
   * Returns the meta object for class '{@link bsql2sql.bSQL2SQL.BSOperation <em>BS Operation</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>BS Operation</em>'.
   * @see bsql2sql.bSQL2SQL.BSOperation
   * @generated
   */
  EClass getBSOperation();

  /**
   * Returns the meta object for the containment reference '{@link bsql2sql.bSQL2SQL.BSOperation#getBop <em>Bop</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Bop</em>'.
   * @see bsql2sql.bSQL2SQL.BSOperation#getBop()
   * @see #getBSOperation()
   * @generated
   */
  EReference getBSOperation_Bop();

  /**
   * Returns the meta object for the containment reference '{@link bsql2sql.bSQL2SQL.BSOperation#getVop <em>Vop</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Vop</em>'.
   * @see bsql2sql.bSQL2SQL.BSOperation#getVop()
   * @see #getBSOperation()
   * @generated
   */
  EReference getBSOperation_Vop();

  /**
   * Returns the meta object for class '{@link bsql2sql.bSQL2SQL.BoolOperation <em>Bool Operation</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Bool Operation</em>'.
   * @see bsql2sql.bSQL2SQL.BoolOperation
   * @generated
   */
  EClass getBoolOperation();

  /**
   * Returns the meta object for the attribute '{@link bsql2sql.bSQL2SQL.BoolOperation#getOp_name <em>Op name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Op name</em>'.
   * @see bsql2sql.bSQL2SQL.BoolOperation#getOp_name()
   * @see #getBoolOperation()
   * @generated
   */
  EAttribute getBoolOperation_Op_name();

  /**
   * Returns the meta object for the attribute list '{@link bsql2sql.bSQL2SQL.BoolOperation#getPList <em>PList</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute list '<em>PList</em>'.
   * @see bsql2sql.bSQL2SQL.BoolOperation#getPList()
   * @see #getBoolOperation()
   * @generated
   */
  EAttribute getBoolOperation_PList();

  /**
   * Returns the meta object for the containment reference list '{@link bsql2sql.bSQL2SQL.BoolOperation#getParams <em>Params</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Params</em>'.
   * @see bsql2sql.bSQL2SQL.BoolOperation#getParams()
   * @see #getBoolOperation()
   * @generated
   */
  EReference getBoolOperation_Params();

  /**
   * Returns the meta object for the containment reference '{@link bsql2sql.bSQL2SQL.BoolOperation#getObjTable <em>Obj Table</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Obj Table</em>'.
   * @see bsql2sql.bSQL2SQL.BoolOperation#getObjTable()
   * @see #getBoolOperation()
   * @generated
   */
  EReference getBoolOperation_ObjTable();

  /**
   * Returns the meta object for the containment reference list '{@link bsql2sql.bSQL2SQL.BoolOperation#getPres <em>Pres</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Pres</em>'.
   * @see bsql2sql.bSQL2SQL.BoolOperation#getPres()
   * @see #getBoolOperation()
   * @generated
   */
  EReference getBoolOperation_Pres();

  /**
   * Returns the meta object for class '{@link bsql2sql.bSQL2SQL.VoidOperation <em>Void Operation</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Void Operation</em>'.
   * @see bsql2sql.bSQL2SQL.VoidOperation
   * @generated
   */
  EClass getVoidOperation();

  /**
   * Returns the meta object for the attribute '{@link bsql2sql.bSQL2SQL.VoidOperation#getOp_name <em>Op name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Op name</em>'.
   * @see bsql2sql.bSQL2SQL.VoidOperation#getOp_name()
   * @see #getVoidOperation()
   * @generated
   */
  EAttribute getVoidOperation_Op_name();

  /**
   * Returns the meta object for the attribute list '{@link bsql2sql.bSQL2SQL.VoidOperation#getPList <em>PList</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute list '<em>PList</em>'.
   * @see bsql2sql.bSQL2SQL.VoidOperation#getPList()
   * @see #getVoidOperation()
   * @generated
   */
  EAttribute getVoidOperation_PList();

  /**
   * Returns the meta object for the containment reference list '{@link bsql2sql.bSQL2SQL.VoidOperation#getParams <em>Params</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Params</em>'.
   * @see bsql2sql.bSQL2SQL.VoidOperation#getParams()
   * @see #getVoidOperation()
   * @generated
   */
  EReference getVoidOperation_Params();

  /**
   * Returns the meta object for the containment reference list '{@link bsql2sql.bSQL2SQL.VoidOperation#getSubs <em>Subs</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Subs</em>'.
   * @see bsql2sql.bSQL2SQL.VoidOperation#getSubs()
   * @see #getVoidOperation()
   * @generated
   */
  EReference getVoidOperation_Subs();

  /**
   * Returns the meta object for class '{@link bsql2sql.bSQL2SQL.BPredicate <em>BPredicate</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>BPredicate</em>'.
   * @see bsql2sql.bSQL2SQL.BPredicate
   * @generated
   */
  EClass getBPredicate();

  /**
   * Returns the meta object for the containment reference '{@link bsql2sql.bSQL2SQL.BPredicate#getPLeft <em>PLeft</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>PLeft</em>'.
   * @see bsql2sql.bSQL2SQL.BPredicate#getPLeft()
   * @see #getBPredicate()
   * @generated
   */
  EReference getBPredicate_PLeft();

  /**
   * Returns the meta object for the attribute '{@link bsql2sql.bSQL2SQL.BPredicate#getPRight <em>PRight</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>PRight</em>'.
   * @see bsql2sql.bSQL2SQL.BPredicate#getPRight()
   * @see #getBPredicate()
   * @generated
   */
  EAttribute getBPredicate_PRight();

  /**
   * Returns the meta object for class '{@link bsql2sql.bSQL2SQL.SQLCall <em>SQL Call</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>SQL Call</em>'.
   * @see bsql2sql.bSQL2SQL.SQLCall
   * @generated
   */
  EClass getSQLCall();

  /**
   * Returns the meta object for the attribute '{@link bsql2sql.bSQL2SQL.SQLCall#getSLeft <em>SLeft</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>SLeft</em>'.
   * @see bsql2sql.bSQL2SQL.SQLCall#getSLeft()
   * @see #getSQLCall()
   * @generated
   */
  EAttribute getSQLCall_SLeft();

  /**
   * Returns the meta object for the attribute '{@link bsql2sql.bSQL2SQL.SQLCall#getSRight <em>SRight</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>SRight</em>'.
   * @see bsql2sql.bSQL2SQL.SQLCall#getSRight()
   * @see #getSQLCall()
   * @generated
   */
  EAttribute getSQLCall_SRight();

  /**
   * Returns the meta object for class '{@link bsql2sql.bSQL2SQL.TableInstance <em>Table Instance</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Table Instance</em>'.
   * @see bsql2sql.bSQL2SQL.TableInstance
   * @generated
   */
  EClass getTableInstance();

  /**
   * Returns the meta object for the attribute '{@link bsql2sql.bSQL2SQL.TableInstance#getTi_name <em>Ti name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Ti name</em>'.
   * @see bsql2sql.bSQL2SQL.TableInstance#getTi_name()
   * @see #getTableInstance()
   * @generated
   */
  EAttribute getTableInstance_Ti_name();

  /**
   * Returns the meta object for the containment reference '{@link bsql2sql.bSQL2SQL.TableInstance#getTi_type <em>Ti type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Ti type</em>'.
   * @see bsql2sql.bSQL2SQL.TableInstance#getTi_type()
   * @see #getTableInstance()
   * @generated
   */
  EReference getTableInstance_Ti_type();

  /**
   * Returns the meta object for class '{@link bsql2sql.bSQL2SQL.TIAssignment <em>TI Assignment</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>TI Assignment</em>'.
   * @see bsql2sql.bSQL2SQL.TIAssignment
   * @generated
   */
  EClass getTIAssignment();

  /**
   * Returns the meta object for the attribute '{@link bsql2sql.bSQL2SQL.TIAssignment#getInstance_name <em>Instance name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Instance name</em>'.
   * @see bsql2sql.bSQL2SQL.TIAssignment#getInstance_name()
   * @see #getTIAssignment()
   * @generated
   */
  EAttribute getTIAssignment_Instance_name();

  /**
   * Returns the meta object for the attribute '{@link bsql2sql.bSQL2SQL.TIAssignment#getInstance_type <em>Instance type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Instance type</em>'.
   * @see bsql2sql.bSQL2SQL.TIAssignment#getInstance_type()
   * @see #getTIAssignment()
   * @generated
   */
  EAttribute getTIAssignment_Instance_type();

  /**
   * Returns the meta object for class '{@link bsql2sql.bSQL2SQL.BParameter <em>BParameter</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>BParameter</em>'.
   * @see bsql2sql.bSQL2SQL.BParameter
   * @generated
   */
  EClass getBParameter();

  /**
   * Returns the meta object for the attribute '{@link bsql2sql.bSQL2SQL.BParameter#getP_name <em>Pname</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Pname</em>'.
   * @see bsql2sql.bSQL2SQL.BParameter#getP_name()
   * @see #getBParameter()
   * @generated
   */
  EAttribute getBParameter_P_name();

  /**
   * Returns the meta object for the containment reference '{@link bsql2sql.bSQL2SQL.BParameter#getType <em>Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Type</em>'.
   * @see bsql2sql.bSQL2SQL.BParameter#getType()
   * @see #getBParameter()
   * @generated
   */
  EReference getBParameter_Type();

  /**
   * Returns the meta object for class '{@link bsql2sql.bSQL2SQL.BSubstitution <em>BSubstitution</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>BSubstitution</em>'.
   * @see bsql2sql.bSQL2SQL.BSubstitution
   * @generated
   */
  EClass getBSubstitution();

  /**
   * Returns the meta object for the attribute '{@link bsql2sql.bSQL2SQL.BSubstitution#getLeft <em>Left</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Left</em>'.
   * @see bsql2sql.bSQL2SQL.BSubstitution#getLeft()
   * @see #getBSubstitution()
   * @generated
   */
  EAttribute getBSubstitution_Left();

  /**
   * Returns the meta object for the containment reference '{@link bsql2sql.bSQL2SQL.BSubstitution#getRight <em>Right</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Right</em>'.
   * @see bsql2sql.bSQL2SQL.BSubstitution#getRight()
   * @see #getBSubstitution()
   * @generated
   */
  EReference getBSubstitution_Right();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  BSQL2SQLFactory getBSQL2SQLFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link bsql2sql.bSQL2SQL.impl.BSQL2SQLImpl <em>BSQL2SQL</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see bsql2sql.bSQL2SQL.impl.BSQL2SQLImpl
     * @see bsql2sql.bSQL2SQL.impl.BSQL2SQLPackageImpl#getBSQL2SQL()
     * @generated
     */
    EClass BSQL2SQL = eINSTANCE.getBSQL2SQL();

    /**
     * The meta object literal for the '{@link bsql2sql.bSQL2SQL.impl.BSQLMachineImpl <em>BSQL Machine</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see bsql2sql.bSQL2SQL.impl.BSQLMachineImpl
     * @see bsql2sql.bSQL2SQL.impl.BSQL2SQLPackageImpl#getBSQLMachine()
     * @generated
     */
    EClass BSQL_MACHINE = eINSTANCE.getBSQLMachine();

    /**
     * The meta object literal for the '<em><b>Mname</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute BSQL_MACHINE__MNAME = eINSTANCE.getBSQLMachine_M_name();

    /**
     * The meta object literal for the '<em><b>Vars</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute BSQL_MACHINE__VARS = eINSTANCE.getBSQLMachine_Vars();

    /**
     * The meta object literal for the '<em><b>Inv</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference BSQL_MACHINE__INV = eINSTANCE.getBSQLMachine_Inv();

    /**
     * The meta object literal for the '<em><b>Init</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute BSQL_MACHINE__INIT = eINSTANCE.getBSQLMachine_Init();

    /**
     * The meta object literal for the '<em><b>Ops</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference BSQL_MACHINE__OPS = eINSTANCE.getBSQLMachine_Ops();

    /**
     * The meta object literal for the '{@link bsql2sql.bSQL2SQL.impl.BTableImpl <em>BTable</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see bsql2sql.bSQL2SQL.impl.BTableImpl
     * @see bsql2sql.bSQL2SQL.impl.BSQL2SQLPackageImpl#getBTable()
     * @generated
     */
    EClass BTABLE = eINSTANCE.getBTable();

    /**
     * The meta object literal for the '<em><b>Table name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute BTABLE__TABLE_NAME = eINSTANCE.getBTable_Table_name();

    /**
     * The meta object literal for the '<em><b>Attributes</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference BTABLE__ATTRIBUTES = eINSTANCE.getBTable_Attributes();

    /**
     * The meta object literal for the '{@link bsql2sql.bSQL2SQL.impl.AttributeImpl <em>Attribute</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see bsql2sql.bSQL2SQL.impl.AttributeImpl
     * @see bsql2sql.bSQL2SQL.impl.BSQL2SQLPackageImpl#getAttribute()
     * @generated
     */
    EClass ATTRIBUTE = eINSTANCE.getAttribute();

    /**
     * The meta object literal for the '<em><b>Att name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ATTRIBUTE__ATT_NAME = eINSTANCE.getAttribute_Att_name();

    /**
     * The meta object literal for the '<em><b>Type</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ATTRIBUTE__TYPE = eINSTANCE.getAttribute_Type();

    /**
     * The meta object literal for the '{@link bsql2sql.bSQL2SQL.impl.BTypeImpl <em>BType</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see bsql2sql.bSQL2SQL.impl.BTypeImpl
     * @see bsql2sql.bSQL2SQL.impl.BSQL2SQLPackageImpl#getBType()
     * @generated
     */
    EClass BTYPE = eINSTANCE.getBType();

    /**
     * The meta object literal for the '<em><b>Type name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute BTYPE__TYPE_NAME = eINSTANCE.getBType_Type_name();

    /**
     * The meta object literal for the '{@link bsql2sql.bSQL2SQL.impl.BSOperationImpl <em>BS Operation</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see bsql2sql.bSQL2SQL.impl.BSOperationImpl
     * @see bsql2sql.bSQL2SQL.impl.BSQL2SQLPackageImpl#getBSOperation()
     * @generated
     */
    EClass BS_OPERATION = eINSTANCE.getBSOperation();

    /**
     * The meta object literal for the '<em><b>Bop</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference BS_OPERATION__BOP = eINSTANCE.getBSOperation_Bop();

    /**
     * The meta object literal for the '<em><b>Vop</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference BS_OPERATION__VOP = eINSTANCE.getBSOperation_Vop();

    /**
     * The meta object literal for the '{@link bsql2sql.bSQL2SQL.impl.BoolOperationImpl <em>Bool Operation</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see bsql2sql.bSQL2SQL.impl.BoolOperationImpl
     * @see bsql2sql.bSQL2SQL.impl.BSQL2SQLPackageImpl#getBoolOperation()
     * @generated
     */
    EClass BOOL_OPERATION = eINSTANCE.getBoolOperation();

    /**
     * The meta object literal for the '<em><b>Op name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute BOOL_OPERATION__OP_NAME = eINSTANCE.getBoolOperation_Op_name();

    /**
     * The meta object literal for the '<em><b>PList</b></em>' attribute list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute BOOL_OPERATION__PLIST = eINSTANCE.getBoolOperation_PList();

    /**
     * The meta object literal for the '<em><b>Params</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference BOOL_OPERATION__PARAMS = eINSTANCE.getBoolOperation_Params();

    /**
     * The meta object literal for the '<em><b>Obj Table</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference BOOL_OPERATION__OBJ_TABLE = eINSTANCE.getBoolOperation_ObjTable();

    /**
     * The meta object literal for the '<em><b>Pres</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference BOOL_OPERATION__PRES = eINSTANCE.getBoolOperation_Pres();

    /**
     * The meta object literal for the '{@link bsql2sql.bSQL2SQL.impl.VoidOperationImpl <em>Void Operation</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see bsql2sql.bSQL2SQL.impl.VoidOperationImpl
     * @see bsql2sql.bSQL2SQL.impl.BSQL2SQLPackageImpl#getVoidOperation()
     * @generated
     */
    EClass VOID_OPERATION = eINSTANCE.getVoidOperation();

    /**
     * The meta object literal for the '<em><b>Op name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute VOID_OPERATION__OP_NAME = eINSTANCE.getVoidOperation_Op_name();

    /**
     * The meta object literal for the '<em><b>PList</b></em>' attribute list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute VOID_OPERATION__PLIST = eINSTANCE.getVoidOperation_PList();

    /**
     * The meta object literal for the '<em><b>Params</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference VOID_OPERATION__PARAMS = eINSTANCE.getVoidOperation_Params();

    /**
     * The meta object literal for the '<em><b>Subs</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference VOID_OPERATION__SUBS = eINSTANCE.getVoidOperation_Subs();

    /**
     * The meta object literal for the '{@link bsql2sql.bSQL2SQL.impl.BPredicateImpl <em>BPredicate</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see bsql2sql.bSQL2SQL.impl.BPredicateImpl
     * @see bsql2sql.bSQL2SQL.impl.BSQL2SQLPackageImpl#getBPredicate()
     * @generated
     */
    EClass BPREDICATE = eINSTANCE.getBPredicate();

    /**
     * The meta object literal for the '<em><b>PLeft</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference BPREDICATE__PLEFT = eINSTANCE.getBPredicate_PLeft();

    /**
     * The meta object literal for the '<em><b>PRight</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute BPREDICATE__PRIGHT = eINSTANCE.getBPredicate_PRight();

    /**
     * The meta object literal for the '{@link bsql2sql.bSQL2SQL.impl.SQLCallImpl <em>SQL Call</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see bsql2sql.bSQL2SQL.impl.SQLCallImpl
     * @see bsql2sql.bSQL2SQL.impl.BSQL2SQLPackageImpl#getSQLCall()
     * @generated
     */
    EClass SQL_CALL = eINSTANCE.getSQLCall();

    /**
     * The meta object literal for the '<em><b>SLeft</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute SQL_CALL__SLEFT = eINSTANCE.getSQLCall_SLeft();

    /**
     * The meta object literal for the '<em><b>SRight</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute SQL_CALL__SRIGHT = eINSTANCE.getSQLCall_SRight();

    /**
     * The meta object literal for the '{@link bsql2sql.bSQL2SQL.impl.TableInstanceImpl <em>Table Instance</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see bsql2sql.bSQL2SQL.impl.TableInstanceImpl
     * @see bsql2sql.bSQL2SQL.impl.BSQL2SQLPackageImpl#getTableInstance()
     * @generated
     */
    EClass TABLE_INSTANCE = eINSTANCE.getTableInstance();

    /**
     * The meta object literal for the '<em><b>Ti name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TABLE_INSTANCE__TI_NAME = eINSTANCE.getTableInstance_Ti_name();

    /**
     * The meta object literal for the '<em><b>Ti type</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference TABLE_INSTANCE__TI_TYPE = eINSTANCE.getTableInstance_Ti_type();

    /**
     * The meta object literal for the '{@link bsql2sql.bSQL2SQL.impl.TIAssignmentImpl <em>TI Assignment</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see bsql2sql.bSQL2SQL.impl.TIAssignmentImpl
     * @see bsql2sql.bSQL2SQL.impl.BSQL2SQLPackageImpl#getTIAssignment()
     * @generated
     */
    EClass TI_ASSIGNMENT = eINSTANCE.getTIAssignment();

    /**
     * The meta object literal for the '<em><b>Instance name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TI_ASSIGNMENT__INSTANCE_NAME = eINSTANCE.getTIAssignment_Instance_name();

    /**
     * The meta object literal for the '<em><b>Instance type</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TI_ASSIGNMENT__INSTANCE_TYPE = eINSTANCE.getTIAssignment_Instance_type();

    /**
     * The meta object literal for the '{@link bsql2sql.bSQL2SQL.impl.BParameterImpl <em>BParameter</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see bsql2sql.bSQL2SQL.impl.BParameterImpl
     * @see bsql2sql.bSQL2SQL.impl.BSQL2SQLPackageImpl#getBParameter()
     * @generated
     */
    EClass BPARAMETER = eINSTANCE.getBParameter();

    /**
     * The meta object literal for the '<em><b>Pname</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute BPARAMETER__PNAME = eINSTANCE.getBParameter_P_name();

    /**
     * The meta object literal for the '<em><b>Type</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference BPARAMETER__TYPE = eINSTANCE.getBParameter_Type();

    /**
     * The meta object literal for the '{@link bsql2sql.bSQL2SQL.impl.BSubstitutionImpl <em>BSubstitution</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see bsql2sql.bSQL2SQL.impl.BSubstitutionImpl
     * @see bsql2sql.bSQL2SQL.impl.BSQL2SQLPackageImpl#getBSubstitution()
     * @generated
     */
    EClass BSUBSTITUTION = eINSTANCE.getBSubstitution();

    /**
     * The meta object literal for the '<em><b>Left</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute BSUBSTITUTION__LEFT = eINSTANCE.getBSubstitution_Left();

    /**
     * The meta object literal for the '<em><b>Right</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference BSUBSTITUTION__RIGHT = eINSTANCE.getBSubstitution_Right();

  }

} //BSQL2SQLPackage
