/*
 * generated by Xtext 2.10.0
 */
package secureuml2Java.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractSecureUML2JavaScopeProvider extends DelegatingScopeProvider {
}
