/**
 * generated by Xtext 2.10.0
 */
package secureuml2SQL.ui.contentassist;

import secureuml2SQL.ui.contentassist.AbstractSecureUML2SQLProposalProvider;

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
@SuppressWarnings("all")
public class SecureUML2SQLProposalProvider extends AbstractSecureUML2SQLProposalProvider {
}
