/*
 * generated by Xtext 2.10.0
 */
package bsql2java.parser.antlr;

import bsql2java.parser.antlr.internal.InternalBSQL2JavaParser;
import bsql2java.services.BSQL2JavaGrammarAccess;
import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

public class BSQL2JavaParser extends AbstractAntlrParser {

	@Inject
	private BSQL2JavaGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalBSQL2JavaParser createParser(XtextTokenStream stream) {
		return new InternalBSQL2JavaParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "BSQL2Java";
	}

	public BSQL2JavaGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(BSQL2JavaGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
