/**
 * generated by Xtext 2.10.0
 */
package secureuml2SQL.secureUML2SQL;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>BE Set</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link secureuml2SQL.secureUML2SQL.BESet#getSet_name <em>Set name</em>}</li>
 *   <li>{@link secureuml2SQL.secureUML2SQL.BESet#getValues <em>Values</em>}</li>
 * </ul>
 *
 * @see secureuml2SQL.secureUML2SQL.SecureUML2SQLPackage#getBESet()
 * @model
 * @generated
 */
public interface BESet extends EObject
{
  /**
   * Returns the value of the '<em><b>Set name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Set name</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Set name</em>' attribute.
   * @see #setSet_name(String)
   * @see secureuml2SQL.secureUML2SQL.SecureUML2SQLPackage#getBESet_Set_name()
   * @model
   * @generated
   */
  String getSet_name();

  /**
   * Sets the value of the '{@link secureuml2SQL.secureUML2SQL.BESet#getSet_name <em>Set name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Set name</em>' attribute.
   * @see #getSet_name()
   * @generated
   */
  void setSet_name(String value);

  /**
   * Returns the value of the '<em><b>Values</b></em>' containment reference list.
   * The list contents are of type {@link secureuml2SQL.secureUML2SQL.BSetValue}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Values</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Values</em>' containment reference list.
   * @see secureuml2SQL.secureUML2SQL.SecureUML2SQLPackage#getBESet_Values()
   * @model containment="true"
   * @generated
   */
  EList<BSetValue> getValues();

} // BESet
