/**
 * generated by Xtext 2.10.0
 */
package secureuml2SQL.secureUML2SQL;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>BMachine</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link secureuml2SQL.secureUML2SQL.BMachine#getM_name <em>Mname</em>}</li>
 *   <li>{@link secureuml2SQL.secureUML2SQL.BMachine#getEsets <em>Esets</em>}</li>
 *   <li>{@link secureuml2SQL.secureUML2SQL.BMachine#getCons <em>Cons</em>}</li>
 *   <li>{@link secureuml2SQL.secureUML2SQL.BMachine#getPros <em>Pros</em>}</li>
 * </ul>
 *
 * @see secureuml2SQL.secureUML2SQL.SecureUML2SQLPackage#getBMachine()
 * @model
 * @generated
 */
public interface BMachine extends SecureUML2SQL
{
  /**
   * Returns the value of the '<em><b>Mname</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Mname</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Mname</em>' attribute.
   * @see #setM_name(String)
   * @see secureuml2SQL.secureUML2SQL.SecureUML2SQLPackage#getBMachine_M_name()
   * @model
   * @generated
   */
  String getM_name();

  /**
   * Sets the value of the '{@link secureuml2SQL.secureUML2SQL.BMachine#getM_name <em>Mname</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Mname</em>' attribute.
   * @see #getM_name()
   * @generated
   */
  void setM_name(String value);

  /**
   * Returns the value of the '<em><b>Esets</b></em>' containment reference list.
   * The list contents are of type {@link secureuml2SQL.secureUML2SQL.BESet}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Esets</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Esets</em>' containment reference list.
   * @see secureuml2SQL.secureUML2SQL.SecureUML2SQLPackage#getBMachine_Esets()
   * @model containment="true"
   * @generated
   */
  EList<BESet> getEsets();

  /**
   * Returns the value of the '<em><b>Cons</b></em>' containment reference list.
   * The list contents are of type {@link secureuml2SQL.secureUML2SQL.BConstant}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Cons</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Cons</em>' containment reference list.
   * @see secureuml2SQL.secureUML2SQL.SecureUML2SQLPackage#getBMachine_Cons()
   * @model containment="true"
   * @generated
   */
  EList<BConstant> getCons();

  /**
   * Returns the value of the '<em><b>Pros</b></em>' containment reference list.
   * The list contents are of type {@link secureuml2SQL.secureUML2SQL.BProperties}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Pros</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Pros</em>' containment reference list.
   * @see secureuml2SQL.secureUML2SQL.SecureUML2SQLPackage#getBMachine_Pros()
   * @model containment="true"
   * @generated
   */
  EList<BProperties> getPros();

} // BMachine
