/**
 * generated by Xtext 2.10.0
 */
package secureuml2SQL.secureUML2SQL;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>BProperties</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link secureuml2SQL.secureUML2SQL.BProperties#getCons <em>Cons</em>}</li>
 *   <li>{@link secureuml2SQL.secureUML2SQL.BProperties#getProp <em>Prop</em>}</li>
 *   <li>{@link secureuml2SQL.secureUML2SQL.BProperties#getPairs <em>Pairs</em>}</li>
 * </ul>
 *
 * @see secureuml2SQL.secureUML2SQL.SecureUML2SQLPackage#getBProperties()
 * @model
 * @generated
 */
public interface BProperties extends EObject
{
  /**
   * Returns the value of the '<em><b>Cons</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Cons</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Cons</em>' attribute.
   * @see #setCons(String)
   * @see secureuml2SQL.secureUML2SQL.SecureUML2SQLPackage#getBProperties_Cons()
   * @model
   * @generated
   */
  String getCons();

  /**
   * Sets the value of the '{@link secureuml2SQL.secureUML2SQL.BProperties#getCons <em>Cons</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Cons</em>' attribute.
   * @see #getCons()
   * @generated
   */
  void setCons(String value);

  /**
   * Returns the value of the '<em><b>Prop</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Prop</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Prop</em>' attribute.
   * @see #setProp(String)
   * @see secureuml2SQL.secureUML2SQL.SecureUML2SQLPackage#getBProperties_Prop()
   * @model
   * @generated
   */
  String getProp();

  /**
   * Sets the value of the '{@link secureuml2SQL.secureUML2SQL.BProperties#getProp <em>Prop</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Prop</em>' attribute.
   * @see #getProp()
   * @generated
   */
  void setProp(String value);

  /**
   * Returns the value of the '<em><b>Pairs</b></em>' containment reference list.
   * The list contents are of type {@link secureuml2SQL.secureUML2SQL.BTuple}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Pairs</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Pairs</em>' containment reference list.
   * @see secureuml2SQL.secureUML2SQL.SecureUML2SQLPackage#getBProperties_Pairs()
   * @model containment="true"
   * @generated
   */
  EList<BTuple> getPairs();

} // BProperties
